name: Tests

on:
  pull_request:

jobs:
  build:
    name: Lib tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: install dependency
      run: |
        chmod +x install.sh
        sudo ./install.sh --dependency
    - name: run tests
      run: |
        .lua/bin/lua test.lua
