name: Tests

on:
  pull_request:

jobs:
  build:
    name: Lib tests
    runs-on: ubuntu-latest
    steps:
    - name: Get LUA
      uses: leafo/gh-actions-lua@v6
      with:
        luaVersion: 5.3
      run: |
        lua5.3 test.lua

