name: Tests

on:
  pull_request:

jobs:
  build:
    name: Lib tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: install dependency
      run: |
        chmod +x install.sh
        sudo ./install.sh --dependency
        sudo apt-get install lua5.1 liblua5.1-dev luarocks luajit
        sudo luarocks install --server=https://luarocks.org/dev luaffi
    - name: run tests
      run: |
        lua5.1 test.lua
