name: Tests

on:
  pull_request:

jobs:
  build:
    name: Lib tests
    runs-on: ubuntu-latest
    steps:
    - name: Get LUA
      uses: leafo/gh-actions-lua@v6
      with:
        luaVersion: 5.2
      id: lua
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: clone and build hub CI tool
      run: |
        lua test.lua
